from .opendtect import *
from .xy_to_grid import *
from .iesx import *
from .surfer import read_surfer
from .zmap import *
from .unmap import unmap_to_dataarray
from .closure import find_closures
from .random import *
from .xarray import GridInfo, SurfaceAccessor
from .logo import plot


from pkg_resources import get_distribution, DistributionNotFound
try:
    VERSION = get_distribution(__name__).version
except DistributionNotFound:
    try:
        from ._version import version as VERSION
    except ImportError:
        raise ImportError(
            "Failed to find (autogenerated) _version.py. "
            "This might be because you are installing from GitHub's tarballs, "
            "use the PyPI ones."
            )
__version__ = VERSION
